### ISSUE TITLE
x265 support

### ISSUE THREAD

**Issue by wantija** [matanui159/ReplaySorcery#105]
Unsure about potential licence or distribution of it, but would x265 support be something to added? It performs a lot better than AMD's x264 implementation.

**Comment by matanui159** [comment]
Experimental HEVC (also know as H.265) support was added in the latest release and can be enabled with `videoEncoder = hevc` (just noticed that I forgot to document it).

Not sure about licensing but I think (IANAL) its fine being that it uses the distributions build of x265 (or the graphics card hardware implementation) rather than distributing the library itself.
