### ISSUE TITLE
Create a Flatpak

### ISSUE THREAD

**Issue by Victor239** [matanui159/ReplaySorcery#108]
Suggesting as an alternative to https://github.com/matanui159/ReplaySorcery/issues/103 since Flatpak works on all Linux distributions, rather than a PPA which only works on the Ubuntu family.

**Comment by Calinou** [comment]
Due to sandboxing limitations, I'm not sure if that's technically feasible. Flatpak is great for desktop applications, but it kind of falls flat for anything that needs full control over the system.

**Comment by matanui159** [comment]
Basically what @Calinou said. I have considered doing something like [holy-build-box](https://github.com/phusion/holy-build-box) where I build on a really old version of Linux so that it links against old libraries and hopefully support more systems.

**Comment by Victor239** [comment]
Ah fair enough. The sandbox can be [relaxed](https://docs.flatpak.org/en/latest/sandbox-permissions.html) to a large extent but I'm not quite sure what RS requires. 

How about Docker instead then? That's the other most common method of cross-distro platform support and is very actively maintained. This way you can ensure every user uses the same library to run your program.

**Comment by matanui159** [comment]
Docker is also sandboxed. I need to be able to capture the screen either via X11 or KMS (which require alot more permissions), and also require access to VA-API for hardware acceleration. I haven't looked into it too much but its very likely using any sandboxed solution either would be difficult or require removing the sandboxed feature.

There is also solutions like AppImage that bundle libraries but do not sandbox the process. However, there is also the problem with any of these solutions is that I would have to bundle an H.264 encoder which means either using OpenH264 (which has terrible quality) or potentially paying licensing fees.

This is why I like the idea of per-distro distributions or something like holy-build-box since they all still use the libraries already on the distro so I can avoid licensing fees and complications.

**Comment by Victor239** [comment]
Ah, I see. I'm not familiar with holy-build-box which is why I suggested more popular alternatives, but reading more on it's usecases I can see why you'd like to use it instead here. 

HBB binaries or a PPA would be great to see, thanks for the informative discussion.
