### ISSUE TITLE
No audio devices

### ISSUE THREAD

**Issue by joelkwiecinski** [matanui159/ReplaySorcery#34]
I went through all the steps for a successful ReplaySorcery installation and it works amazingly well on my computer to record my screen.
The problem I am having is that it does not detect any audio device when starting the program.

![Captura de pantalla de 2020-09-27 01-29-26](https://user-images.githubusercontent.com/71956664/94356096-ef80fb00-0060-11eb-8769-0dd209463ced.png)

I have pavucontrol installed but nothing appears in the recording tab when I am running ReplaySorcery.

I apologize in advance if this is due to a mistake that I have made, but I believe I have followed all the steps correctly.
I am currently using Pop! _OS 20.04 LTS.

**Comment by matanui159** [comment]
Not sure why this would be, right now it uses SDL2 which internally uses pulseaudio so as long as that can see the devices, ReplaySorcery should be able to as well. @pseregiet might know more since they implemented to audio recording.

**Comment by pseregiet** [comment]
Can you show what you have in pavucontrol in Input Devices. Select "Show All input devices" at the bottom
![2020-09-29-113118_1079x858_scrot](https://user-images.githubusercontent.com/11596839/94541141-84dde400-0247-11eb-82b6-fee15683b2ab.png)

**Comment by joelkwiecinski** [comment]
Sure!

![Captura de pantalla de 2020-09-29 07-13-45](https://user-images.githubusercontent.com/71956664/94545768-5e0db680-0223-11eb-92d5-6cdb40f5d7d7.png)

I reinstalled my system (i'm still using Pop 20.04) for other reasons, reinstalled ReplaySorcery and the problem remains.
Sorry if my english is bad, I speak spanish and use the translator sometimes.

**Comment by pseregiet** [comment]
Well, it seems ok, you have the monitor of your main audio device. Weird SDL doesn't see that. I can prepare some debug build with some extra logs and if you can run it it'd be great

**Comment by joelkwiecinski** [comment]
Of course, just tell me what to do and what results to send you so you can try to figure it out. No problem

**Comment by pseregiet** [comment]
[replay-sorcery.zip](https://github.com/matanui159/ReplaySorcery/files/5298577/replay-sorcery.zip)
extract it and run it from a terminal (./replay-sorcery) and paste the output

**Comment by joelkwiecinski** [comment]
./replay-sorcery: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./replay-sorcery)

Tried "sudo apt-get install libc6" but 

libc6 is already the newest version (2.31-0ubuntu9.1).

**Comment by pseregiet** [comment]
I see, I'm on Manjaro with a newer glibc, I'll try to compile with the older version

**Comment by pseregiet** [comment]
Where did you get this program from ? Did you build it yourself or did you download it from some repository (aur for example) ? Perhaps the build you have does not have the pulseaudio backend build in. To test try running this command in the directory where your replay-sorcery is installed (`which replay-sorcery` to find out)

`strings ./replay-sorcery | grep "PulseAudio"`

this is what you should get. If something is missing, the build is probably bad

```
[seregiet@seregiet-pc bin]$ strings ./replay-sorcery | grep "PulseAudio"
PulseAudio
Could not setup connection to PulseAudio
Could not connect to PulseAudio
Requested PulseAudio sink/source missing?
Could not set up PulseAudio stream
Could not connect PulseAudio stream
Could not connect to PulseAudio server
LoadPulseAudioLibrary
UnloadPulseAudioLibrary
```

**Comment by joelkwiecinski** [comment]
I see. I built it myself with the steps I saw in the GitHub project. It may be that there was a problem with that, although I have not seen errors in the compilation. I tried to download it from some repository but could not get it because Pop OS is not Arch, I am still something new to Linux and not long ago I use it as my daily system.

Sorry again if this is due to a mistake that I have made.

**Comment by pseregiet** [comment]
No, I didn't want to imply you did something wrong, just trying to figure out what's going on. I've discovered that if you don't have the required pulseaudio libraries and headers installed, SDL2 will not discover them and will compile without pulseaudio support. Without it, you will not get any sound. Or, I should say, it will fallback to some other audio driver (like JACK or OSS) and try using that, but there's a possibility it didn't discover anything and you just have a build without a sound.
I was under the impression that you don't need any pulse audio libraries when building, since SDL2 can load those libraries at runtime, instead of linking them to the executable, but you need the library on the disk at least for the autoconfigure script to detect that you indeed have pulse audio and want that part of the code compiled. I will try to fix that, make it so you don't need pulseaudio installed while building for it to work.

With all that said, you obviously have pulse audio installed since you have sound in all other applications and you have pavucontrol working. So, check if your build has the pulse audio code included. Go to your build folder and there you should have bin/replay-sorcery file. Run that strings command on it and see the output.
`strings ./bin/replay-sorcery | grep "PulseAudio"`
If you get a bunch of strings that means your build has pulse audio enabled. Why you get no devices is still a unknown.
If you get nothing, it means your build does not have pulse audio code included. Try installing libpulse-dev and then build again from scratch.

**Comment by joelkwiecinski** [comment]
Yessssssssss! You definitely know what you do. I installed pulse audio libraries (libpulse-dev) and then compiled ReplaySorcery from 0  and now it detects my sound devices perfectly! I just have to do tests but I have no doubt that it will work perfectly, the screen recording is great.

![Captura de pantalla de 2020-10-01 07-43-31](https://user-images.githubusercontent.com/71956664/94800043-6c420b00-03ba-11eb-9a77-02fade3fa683.png)

I really appreciate your help and consider this to be an excellent project for Linux.
