### ISSUE TITLE
Can I use system installed libjpeg, sdl2, fdk-acc instead of bundled modules?

### ISSUE THREAD

**Issue by kevinsmia1939** [matanui159/ReplaySorcery#72]
Hello,

I would like to know if I can use system installed libjpeg, sdl2, fdk-acc instead of pulling external module from git.
Are there cmake flag that I can use or not? I am asking this because using system installed dependencies is more preferable form linux packaging, so maybe in the future it will be more convenient for anyone who want to package this software.

Kind regards,
Andy.

**Comment by matanui159** [comment]
There are a couple of problems with using system packages:
- `libjpeg`, most package managers don't specify if it is `libjpeg` (very slow) or `libjpeg-turbo` (very fast, the one we use)
- `sdl2`, we use a patched version of SDL2
- `libbacktrace`, most package managers either don't have this or is outdated
- it helps prevent issues with versioning (I have an older/newer/different version of this package and it won't work)

With the `ffmpeg` branch however (which is getting very close to completion, just fixing some audio issues), the only dependencies are FFmpeg and `libbacktrace`. The former is too large to bundle in so is using the system version and the later is still using the submodule because of the above reasons.
