### ISSUE TITLE
Alternate path for the configuration file

### ISSUE THREAD

**Issue by benjamimgois** [matanui159/ReplaySorcery#77]
Hi @matanui159 ,

Since i think replaySorcery is a really nice application and deserves to be widely spread and used in Linux gaming communities, i created the GUI for replaySorcery inside Goverlay. All the configurations were directed to the replay-sorcery.conf inside the `.config` folder. The move to the `/usr/..` folder in the 0.4.1 build made the requirement of the root password to save new configuration files. 

To keep things nice and simple for users, i would suggest to use the same solution adopted by Mangohud and vkBasalt. If the system doesn't locate the config file inside the `/usr/... `folder, it should also look for it $HOME/.config/ folder as an alternative path. This way users shouldn't have to worry about security or trust issues providing the root password just to make small change to the app.

Here is the GUI in the latest Goverlay build, also be my guest for any observations or alterations you think might better suit replaySorcery.

![image](https://user-images.githubusercontent.com/7688496/102821840-93571a00-43b6-11eb-8dbe-3f1dbd56bf45.png)

**Comment by matanui159** [comment]
The problem is that a default config file is installed into the `/usr/local/etc` directory to provide as both documentation and so you can easily find where it is. In the older versions it would read from multiple locations and each one would override settings in the previous ones but that made the code confusing and is not common behavior in Linux programs.

Most of the complexity was supporting the XDG specification so instead we could just do a global file and a `~/.config`. Alternatively it could just use the `~/.config` file if it exists and if it doesn't it will use the global one.

**Comment by matanui159** [comment]
Or I could just bring back the XDG specification and just have `/usr/local/etc` as well but if I did that I would do it in an external library to make things cleaner.

**Comment by matanui159** [comment]
Had a bit of free time this morning so I put in a simple solution of a global/local file pair. There is one more change I want to make before making a new release but you can checkout master if you want to test with it.

**Comment by benjamimgois** [comment]
Thanks a lot @matanui159. I'll make some tests in the master build and report later.
