### ISSUE TITLE
XDG_VIDEOS_DIR isn't used

### ISSUE THREAD

**Issue by SleeplessSloth** [matanui159/ReplaySorcery#81]
I have XDG_VIDEOS_DIR set to `$HOME/` in `~/.config/user-dirs.dirs` yet replay-sorcery tries to write to the default `~/Videos` (and fails). It should check `XDG_VIDEOS_DIR` first and only then fallback to `~/Videos` or maybe even `~/`

### Log
```
Dec 23 15:47:21 zeus replay-sorcery[17697]: Saving video to '/home/gray/Videos/ReplaySorcery_2020-12-23_15-47-21.mp4'...
Dec 23 15:47:21 zeus replay-sorcery[17697]: [mp4 @ 0x55fa0e6c8c80] Failed to open output: No such file or directory
Dec 23 15:47:22 zeus replay-sorcery[17697]: Failed to output video: No such file or directory
```

P.S. Yes, I know I can change it in the config file but the defaults fit me pretty well, so I don't really want to change anything. The program should detect the default Videos dir automatically.

**Comment by matanui159** [comment]
I looked into this and my only concern is that currently the directory and filename is a singular option `outputFile`. If I were to implement this I would need to split it into two and have the output directory automatically detected by default and then deal with backwards compatibility since the options will be changing and at that point I genuinely don't think its worth it. I myself don't even use the videos directory for replay-sorcery videos, `~/Videos` is just a nice default that works for most users without them having to tinker with settings and more advanced users can change the directory and filename pattern with `outputFile`.
